const ActionTypes = {
  CLICK_SEARCH_MOVIES_BUTTON: 'CLICK_SEARCH_MOVIES_BUTTON',
  RECEIVE_MOVIES_LIST: 'RECEIVE_MOVIES_LIST',
  RECEIVE_MOVIES_LIST_FAILURE: 'RECEIVE_MOVIES_LIST_FAILURE',
  CLICK_MOVIE_ITEM: 'CLICK_MOVIE_ITEM',
  RECEIVE_MOVIE_DETAIL: 'RECEIVE_MOVIE_DETAIL',
  RECEIVE_MOVIES_DETAIL_FAILURE: 'RECEIVE_MOVIES_DETAIL_FAILURE',
};

export default ActionTypes;
